FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY . .

RUN npm i
# RUN npm run build
# If you are building your code for production
# RUN npm ci --omit=dev

CMD ["npx", "vite", "--port=3000", "--host=0.0.0.0"]