FROM node:18.15

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json .

RUN npm i
RUN npm i -g nodemon
# RUN npm run build
# If you are building your code for production
# RUN npm ci --omit=dev

COPY . .

CMD ["nodemon", "-L", "server.js"]